name: Deploy Maven Site to GitHub Pages with gh

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build and generate Maven site
        run: mvn clean site

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt-get update
          sudo apt-get install gh

      - name: Authenticate gh CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo $GH_TOKEN | gh auth login --with-token

      - name: Publish site to gh-pages branch
        run: |
          gh repo clone ${{ github.repository }} repo-tmp
          cd repo-tmp
          git checkout gh-pages || git checkout --orphan gh-pages
          rm -rf *
          cp -r ../target/site/* .
          git add .
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Deploy Maven site"
          git push origin gh-pages --force