name: Publish & Release

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: write
  packages: write

jobs:
  build-publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java & Maven for GitHub Packages
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build with Maven
        run: mvn clean package

      - name: Publish to GitHub Packages
        run: mvn deploy -DskipTests

      - name: Create Release & Upload JAR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          gh release create "$TAG_NAME" target/*.jar --title "$TAG_NAME" --notes "Release $TAG_NAME" --repo ${{ github.repository }}