name: Release

on:
  push:
    tags:
      - '*.*.*'   # Déclenche sur les tags de type 1.0.0, 2.4.5, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn package

      - name: Upload JAR to Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install GitHub CLI
        uses: cli/cli@latest

      - name: Create GitHub Release via gh CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: |
          TAG_NAME=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
        gh release create "$TAG_NAME" target/*.jar --notes "Release $TAG_NAME"